# Generated by Django 2.2 on 2019-10-19 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wazamoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Waza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toi', models.TextField()),
                ('kai1', models.CharField(max_length=40)),
                ('kai2', models.CharField(default='', max_length=40)),
                ('kai3', models.CharField(default='', max_length=40)),
                ('shutoku', models.BooleanField(default=False)),
                ('wazamoku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mugenjigoku.Wazamoku')),
            ],
        ),
    ]
