# Generated by Django 2.2 on 2019-10-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugenjigoku', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wazamoku',
            old_name='name',
            new_name='daimoku',
        ),
        migrations.RemoveField(
            model_name='waza',
            name='shutoku',
        ),
        migrations.AddField(
            model_name='waza',
            name='rendo',
            field=models.CharField(choices=[('0', 'Mijuku'), ('1', 'Nami'), ('2', 'Jukuren')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='wazamoku',
            name='kotodute',
            field=models.CharField(default='', max_length=40),
        ),
    ]
